/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.pump.graph.core;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.image.BufferedImage;
import java.io.File;
import javax.imageio.ImageIO;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import net.miginfocom.swing.MigLayout;
import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.awt.ActionID;
import org.openide.awt.ActionReference;
import org.openide.modules.InstalledFileLocator;
import org.openide.windows.TopComponent;
import org.openide.util.NbBundle.Messages;

/**
 * Top component which displays something.
 */
@ConvertAsProperties(
        dtd = "-//org.pump.graph.core//StartPage//EN",
        autostore = false
)
@TopComponent.Description(
        preferredID = "StartPageTopComponent",
        //iconBase="SET/PATH/TO/ICON/HERE", 
        persistenceType = TopComponent.PERSISTENCE_ALWAYS
)
@TopComponent.Registration(mode = "editor", openAtStartup = true)
@ActionID(category = "Window", id = "org.pump.graph.core.StartPageTopComponent")
@ActionReference(path = "Menu/Window", position = 0)
@TopComponent.OpenActionRegistration(
        displayName = "#CTL_StartPageAction",
        preferredID = "StartPageTopComponent"
)
@Messages({
    "CTL_StartPageAction=Start Page",
    "CTL_StartPageTopComponent=Start Page",
    "HINT_StartPageTopComponent=Start Page"
})
public final class StartPageTopComponent extends TopComponent {

    public StartPageTopComponent() {
        //initComponents();
        setLayout(new BorderLayout());
        setName(Bundle.CTL_StartPageTopComponent());
        setToolTipText(Bundle.HINT_StartPageTopComponent());
        add(new JScrollPane(new StartPanel()), BorderLayout.CENTER);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    @Override
    public void componentOpened() {
        // TODO add custom code on component opening
    }

    @Override
    public void componentClosed() {
        // TODO add custom code on component closing
    }

    void writeProperties(java.util.Properties p) {
        // better to version settings since initial version as advocated at
        // http://wiki.apidesign.org/wiki/PropertyFiles
        p.setProperty("version", "1.0");
        // TODO store your settings
    }

    void readProperties(java.util.Properties p) {
        String version = p.getProperty("version");
        // TODO read your settings according to their version
    }
}

class StartPanel extends JPanel {
public static BufferedImage image;

    @Override
    protected void paintComponent(Graphics g) {
     //   super.paintComponent(g); //To change body of generated methods, choose Tools | Templates.
    g.drawImage(image, 0,0,getWidth(),getHeight(),null);
    Font font=new Font("Monospaced 12", Font.PLAIN, 36);
    g.setFont(font);
    g.setColor(Color.white);
    g.drawString("Annai Engineering Company",100,100);
    g.drawString("Coimbatore",100,150);
    g.drawString("Pump Performance",100,250);
    repaint();
    }

    public StartPanel() {
        //setLayout(new MigLayout("",
          //      "100[][][]", "100[]50[grow]100"));
       
        
        /*setBackground(new Color(30, 30, 100));
        JLabel l = new JLabel("Annai Engineering Company");
        l.setFont(new Font("Monospaced 12", Font.PLAIN, 36));
        l.setForeground(Color.white);
        add(l, "wrap");
        l = new JLabel("Coimbatore");
        l.setFont(new Font("Monospaced 12", Font.PLAIN, 36));
        l.setForeground(Color.white);
        add(l, "wrap");

        l = new JLabel("Pump Performance");
        l.setFont(new Font("Monospaced 12", Font.PLAIN, 36));
        l.setForeground(Color.white);
        add(l, "wrap");*/
        super();
        setPreferredSize(new Dimension(500, 400));
        try{
            File f= InstalledFileLocator.getDefault().locate("wallpaper.jpg","org.pump.graph.core", false);
            image = ImageIO.read(f);//new File("/org/pump/graph/core/Lions_love.jpg"));
        }catch (Exception ex){
            ex.printStackTrace();;
        }
        
       
    }
}
